### ISSUE TITLE
Revamp the sub operations for list operation

### ISSUE THREAD

**Issue by dinuish94** [wso2-extensions/esb-connector-email#2]
**Description:**
Operations 'getBody' and 'getAttachment' can be called over the payload received from list operation to retrieve email data. However, this may not be self-explanatory or consistent with the current operations model. Also, if the user misses invoking 'list' operation, this may cause confusion. Hence, this model should be revisited.

**Comment by anupama-pathirage** [comment]
Moved this issue to https://github.com/wso2/micro-integrator/issues/3441, hence closign this issue.
