### ISSUE TITLE
Issues with Email Connector on Enterprise Integrator 6.6.0

### ISSUE THREAD

**Issue by ruit478** [wso2-extensions/esb-connector-email#7]
**Description:**
When attempting to execute operations with the email connector, the server reports "Error in instantiating class : org.wso2.carbon.connector.operations.list.EmailGetAttachment". It's important to note that i have attempted to use both the regular connector, as well as building it from source.
**Affected Product Version:**
EI 6.6.0
**Steps to reproduce:**
Just create a project with Email connector and attempt to deploy the corresponding CAR to the server, then try to enable said connector on the server console. Full error log is available at https://pastebin.com/bnhHTsdC

**Comment by bbockhoudt** [comment]
Same error here

**Comment by ruit478** [comment]
> Same error here

Did you find any alternative that allows for attachment extration in emails or is this feature simply not available as of right now?

**Comment by achieverprince** [comment]
Same error here

**Comment by JOELBARASA** [comment]
Same error. Any solution/workaround?

**Comment by FernanCapito** [comment]
Same error here!

**Comment by noah2031** [comment]
Hi guys 
did any one got it solved?


Regards,

**Comment by VasiiH** [comment]
I am also unable to send an email with an attachment, I tried with base64 encoded binary values, it didn't work for me, can anyone give me a solution for that, which the way to send an attachment using email connector?

**Comment by anupama-pathirage** [comment]
Moved the issue https://github.com/wso2/micro-integrator/issues/3439 for better tracking purposes. hence closing this issue.
