### ISSUE TITLE
EmailConnector: Send operation does not work on Enterprise Integrator 6.6.0

### ISSUE THREAD

**Issue by IMarcelF** [wso2-extensions/esb-connector-email#9]
**Description:**

When attempting to execute the operation "send"  of the email connector, the server reports: 

"java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:834) Caused by: java.lang.ClassCastException: class org.wso2.carbon.connector.connection.EmailConnection cannot be cast to class org.wso2.carbon.connector.connection.EmailConnection (org.wso2.carbon.connector.connection.EmailConnection is in unnamed module of loader org.apache.axis2.deployment.DeploymentClassLoader @1a88cbdf; org.wso2.carbon.connector.connection.EmailConnection is in unnamed module of loader org.apache.axis2.deployment.DeploymentClassLoader @86e0036) at org.wso2.carbon.connector.operations.EmailSend.connect(EmailSend.java:58) at org.wso2.carbon.connector.core.AbstractConnector.mediate(AbstractConnector.java:32)". 

**Affected Product Version:**
Email Connector v1.0.0

**OS, DB, other environment details and versions:**    
OS: Linux. EI 6.6.0

**Comment by JOELBARASA** [comment]
Which version of EI  supports EmailConnector send operation?

**Comment by IMarcelF** [comment]
@JOELBARASA i have deployed the solution on EI 6.6.0. According to the documentation [()](https://ei.docs.wso2.com/en/latest/micro-integrator/references/connectors/email-connector/email-connector-overview/) the compatibility is ok. 
Do you have any ideia about the issue ?? Thanks in advanced.
